### ISSUE TITLE
Make sound play on every keystroke

### ISSUE THREAD

**Issue by WebFreak001** [zerojuan/mechanical-keyboard-1#1]
It would be nice if it would always play when I hit a key. Its kind of boring if it only plays every time when the old sound stopped. As the original repo stopped development, I'm going to report it here.

Edit: Maybe also use onkeydown so it wont play over and over when holding a key

**Comment by zerojuan** [comment]
I'm not quiet sure what you mean with the sounds not working. It has 10 sound buffers, so it should allow up to 10 simultaneous sound files playing at the same time: https://github.com/zerojuan/mechanical-keyboard-1/blob/master/lib/key-sound.coffee

I do use the keydown event. Or is there a separate onkeydown listener?https://github.com/zerojuan/mechanical-keyboard-1/blob/master/lib/keyboard-listener.coffee#L29

**Comment by WebFreak001** [comment]
sorry, it was an outdated version. Its fixed now ^^
